# Generated by Django 5.1.3 on 2024-11-30 12:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Untitled Bank Account", max_length=100),
                ),
                ("provider", models.CharField(max_length=100)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("card_number_ends_with", models.IntegerField()),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[("LIGHT", "Light"), ("DARK", "Dark")],
                        default="LIGHT",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("DZD", "Algerian Dinar"),
                            ("AOA", "Angolan Kwanza"),
                            ("BWP", "Botswana Pula"),
                            ("BIF", "Burundi Franc"),
                            ("CVE", "Cape Verde Escudo"),
                            ("XAF", "Central African CFA Franc"),
                            ("KMF", "Comorian Franc"),
                            ("CDF", "Congolese Franc"),
                            ("DJF", "Djiboutian Franc"),
                            ("EGP", "Egyptian Pound"),
                            ("ERN", "Eritrean Nakfa"),
                            ("SZL", "Eswatini Lilangeni"),
                            ("ETB", "Ethiopian Birr"),
                            ("GMD", "Gambian Dalasi"),
                            ("GHS", "Ghanaian Cedi"),
                            ("GNF", "Guinean Franc"),
                            ("KES", "Kenyan Shilling"),
                            ("LSL", "Lesotho Loti"),
                            ("LRD", "Liberian Dollar"),
                            ("LYD", "Libyan Dinar"),
                            ("MGA", "Malagasy Ariary"),
                            ("MWK", "Malawian Kwacha"),
                            ("MRU", "Mauritanian Ouguiya"),
                            ("MUR", "Mauritian Rupee"),
                            ("MAD", "Moroccan Dirham"),
                            ("MZN", "Mozambican Metical"),
                            ("NAD", "Namibian Dollar"),
                            ("NGN", "Nigerian Naira"),
                            ("RWF", "Rwandan Franc"),
                            ("STN", "São Tomé and Príncipe Dobra"),
                            ("SCR", "Seychellois Rupee"),
                            ("SLL", "Sierra Leonean Leone"),
                            ("SOS", "Somali Shilling"),
                            ("ZAR", "South African Rand"),
                            ("SSP", "South Sudanese Pound"),
                            ("SDG", "Sudanese Pound"),
                            ("TZS", "Tanzanian Shilling"),
                            ("TND", "Tunisian Dinar"),
                            ("UGX", "Ugandan Shilling"),
                            ("XOF", "West African CFA Franc"),
                            ("ZMW", "Zambian Kwacha"),
                            ("ZWL", "Zimbabwean Dollar"),
                            ("ARS", "Argentine Peso"),
                            ("BSD", "Bahamian Dollar"),
                            ("BBD", "Barbadian Dollar"),
                            ("BZD", "Belize Dollar"),
                            ("BMD", "Bermudian Dollar"),
                            ("BOB", "Bolivian Boliviano"),
                            ("BRL", "Brazilian Real"),
                            ("CAD", "Canadian Dollar"),
                            ("CLP", "Chilean Peso"),
                            ("COP", "Colombian Peso"),
                            ("CRC", "Costa Rican Colón"),
                            ("CUP", "Cuban Peso"),
                            ("DOP", "Dominican Peso"),
                            ("XCD", "Eastern Caribbean Dollar"),
                            ("USD", "Ecuadorian Dollar"),
                            ("USD", "El Salvador Dollar"),
                            ("FKP", "Falkland Islands Pound"),
                            ("GTQ", "Guatemalan Quetzal"),
                            ("GYD", "Guyanaese Dollar"),
                            ("HTG", "Haitian Gourde"),
                            ("HNL", "Honduran Lempira"),
                            ("JMD", "Jamaican Dollar"),
                            ("MXN", "Mexican Peso"),
                            ("NIO", "Nicaraguan Córdoba"),
                            ("PAB", "Panamanian Balboa"),
                            ("PYG", "Paraguayan Guaraní"),
                            ("PEN", "Peruvian Sol"),
                            ("SRD", "Surinamese Dollar"),
                            ("TTD", "Trinidad and Tobago Dollar"),
                            ("USD", "United States Dollar"),
                            ("UYU", "Uruguayan Peso"),
                            ("VES", "Venezuelan Bolívar"),
                            ("AFN", "Afghan Afghani"),
                            ("AMD", "Armenian Dram"),
                            ("AZN", "Azerbaijani Manat"),
                            ("BHD", "Bahraini Dinar"),
                            ("BDT", "Bangladeshi Taka"),
                            ("BTN", "Bhutanese Ngultrum"),
                            ("BND", "Brunei Dollar"),
                            ("KHR", "Cambodian Riel"),
                            ("CNY", "Chinese Yuan"),
                            ("GEL", "Georgian Lari"),
                            ("HKD", "Hong Kong Dollar"),
                            ("INR", "Indian Rupee"),
                            ("IDR", "Indonesian Rupiah"),
                            ("IRR", "Iranian Rial"),
                            ("IQD", "Iraqi Dinar"),
                            ("ILS", "Israeli New Shekel"),
                            ("JPY", "Japanese Yen"),
                            ("JOD", "Jordanian Dinar"),
                            ("KZT", "Kazakhstani Tenge"),
                            ("KWD", "Kuwaiti Dinar"),
                            ("KGS", "Kyrgyzstani Som"),
                            ("LAK", "Lao Kip"),
                            ("LBP", "Lebanese Pound"),
                            ("MYR", "Malaysian Ringgit"),
                            ("MVR", "Maldivian Rufiyaa"),
                            ("MNT", "Mongolian Tögrög"),
                            ("MMK", "Myanmar Kyat"),
                            ("NPR", "Nepalese Rupee"),
                            ("OMR", "Omani Rial"),
                            ("PKR", "Pakistani Rupee"),
                            ("PHP", "Philippine Peso"),
                            ("QAR", "Qatari Riyal"),
                            ("SAR", "Saudi Riyal"),
                            ("SGD", "Singapore Dollar"),
                            ("KRW", "South Korean Won"),
                            ("LKR", "Sri Lankan Rupee"),
                            ("SYP", "Syrian Pound"),
                            ("TJS", "Tajikistani Somoni"),
                            ("THB", "Thai Baht"),
                            ("TMT", "Turkmenistan Manat"),
                            ("AED", "United Arab Emirates Dirham"),
                            ("UZS", "Uzbekistani Som"),
                            ("VND", "Vietnamese Đồng"),
                            ("YER", "Yemeni Rial"),
                            ("ALL", "Albanian Lek"),
                            ("EUR", "Andorran Euro"),
                            ("BYN", "Belarusian Ruble"),
                            ("BAM", "Bosnia and Herzegovina Convertible Mark"),
                            ("BGN", "Bulgarian Lev"),
                            ("HRK", "Croatian Kuna"),
                            ("CZK", "Czech Koruna"),
                            ("DKK", "Danish Krone"),
                            ("EUR", "Euro"),
                            ("HUF", "Hungarian Forint"),
                            ("ISK", "Icelandic Króna"),
                            ("MKD", "Macedonian Denar"),
                            ("MDL", "Moldovan Leu"),
                            ("EUR", "Montenegrin Euro"),
                            ("NOK", "Norwegian Krone"),
                            ("PLN", "Polish Złoty"),
                            ("RON", "Romanian Leu"),
                            ("RUB", "Russian Ruble"),
                            ("RSD", "Serbian Dinar"),
                            ("CHF", "Swiss Franc"),
                            ("TRY", "Turkish Lira"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("GBP", "United Kingdom Pound"),
                            ("AUD", "Australian Dollar"),
                            ("FJD", "Fijian Dollar"),
                            ("AUD", "Kiribati Dollar"),
                            ("NZD", "New Zealand Dollar"),
                            ("PGK", "Papua New Guinean Kina"),
                            ("WST", "Samoan Tālā"),
                            ("SBD", "Solomon Islands Dollar"),
                            ("TOP", "Tongan Paʻanga"),
                            ("AUD", "Tuvaluan Dollar"),
                            ("VUV", "Vanuatu Vatu"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.settings"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        default="EXPENSE",
                        max_length=10,
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_account",
                        to="core.bankaccount",
                    ),
                ),
                (
                    "from_card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_card",
                        to="core.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
