# Generated by Django 5.1.3 on 2024-11-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_card_card_number_ends_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="provider",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
