ACCOUNT_PROVIDERS_INDIA = [
    {"code": "HDFC", "name": "HDFC Bank"},
    {"code": "ICICI", "name": "ICICI Bank"},
    {"code": "SBI", "name": "State Bank of India"},
    {"code": "AXIS", "name": "Axis Bank"},
    {"code": "KOTAK", "name": "Kotak Mahindra Bank"},
    {"code": "RBL", "name": "RBL Bank"},
    {"code": "YES", "name": "Yes Bank"},
    {"code": "IDFC", "name": "IDFC First Bank"},
    {"code": "IDBI", "name": "IDBI Bank"},
    {"code": "PNB", "name": "Punjab National Bank"},
    {"code": "BOB", "name": "Bank of Baroda"},
    {"code": "BOI", "name": "Bank of India"},
    {"code": "BOM", "name": "Bank of Maharashtra"},
    {"code": "UCO", "name": "UCO Bank"},
    {"code": "UBI", "name": "Union Bank of India"},
    {"code": "UNITED", "name": "United Bank of India"},
    {"code": "VIJAYA", "name": "Vijaya Bank"},
]
